import * as T from "@/types";

export const procedures: T.IVideo[] = [
  {
    id: 0,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 1 - Recepção",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 1,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 2 - Limpeza do Acampamento",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 2,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 3 - Banda",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 3,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 4 - Refeitório",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 4,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 5 - Apoio",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 5,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 6 - PL",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 6,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 7 - Conselho",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 7,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 8 - Auxiliar de Conselho",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 8,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 9 - Secretaria",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 9,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 10 - Enfermaria",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 10,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 11 - Programação",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 11,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 12 - Capelania",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 12,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 13 - Camping Out",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 13,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 14 - Cantina",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
  {
    id: 14,
    videoId: "XqRTiJidKaA",
    videoName: "Procedimento 15 - Piscina",
    formLink: "https://forms.gle/iiag1nAofTb6shsAA",
    videoLink: "https://www.youtube.com/watch?v=XqRTiJidKaA",
  },
];
